# Generated by Django 5.0.14 on 2026-02-02 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='articles.page')),
                ('debut', models.CharField(max_length=250)),
                ('latest', models.CharField(max_length=250)),
            ],
            bases=('articles.page',),
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='articles.page')),
                ('release', models.CharField(max_length=250)),
                ('director', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=250)),
            ],
            bases=('articles.page',),
        ),
    ]
