# Generated by Django 5.0.14 on 2026-02-02 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['created']},
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['-created'], name='articles_pa_created_d76774_idx'),
        ),
    ]
